server:
  port: 9090
# Spring boot application
spring:
  application:
    name: ebusbar-boos
  datasource:
    url: jdbc:mysql://192.168.56.101:3306/im_db?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 888888
    druid:
      stat-view-servlet:
        login-username: ${spring.datasource.username}
        login-password: ${spring.datasource.password}
      aop-patterns: com.ebusbar.boss.provider.service.*
      web-stat-filter:
        session-stat-enable: true
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        profile-enable: true
      filters: wall,stat
      filter:
        wall:
          log-violation: true
          throw-exception: false
      min-idle: 1
      initial-size: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'




mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.netty4.server.entity
logging:
  level:
    com.ebusbar.boss.provider.mapper: debug