package com.netty4.server.mapper;

import com.netty4.server.entity.FriendShipPolicyIm;
import org.apache.ibatis.annotations.Param;

public interface FriendShipPolicyImMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_friend_ship_policy
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_friend_ship_policy
     *
     * @mbg.generated
     */
    int insert(FriendShipPolicyIm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_friend_ship_policy
     *
     * @mbg.generated
     */
    int insertSelective(FriendShipPolicyIm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_friend_ship_policy
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    FriendShipPolicyIm selectByPrimaryKeySelective(@Param("id") Long id, @Param("selective") FriendShipPolicyIm.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_friend_ship_policy
     *
     * @mbg.generated
     */
    FriendShipPolicyIm selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_friend_ship_policy
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FriendShipPolicyIm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_friend_ship_policy
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FriendShipPolicyIm record);
}