package com.netty4.server.mapper;

import com.netty4.server.entity.FriendTypeIm;
import org.apache.ibatis.annotations.Param;

public interface FriendTypeImMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_friend_type
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_friend_type
     *
     * @mbg.generated
     */
    int insert(FriendTypeIm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_friend_type
     *
     * @mbg.generated
     */
    int insertSelective(FriendTypeIm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_friend_type
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    FriendTypeIm selectByPrimaryKeySelective(@Param("id") Long id, @Param("selective") FriendTypeIm.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_friend_type
     *
     * @mbg.generated
     */
    FriendTypeIm selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_friend_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FriendTypeIm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_friend_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FriendTypeIm record);
}