package com.netty4.server.mapper;

import com.netty4.server.entity.GroupMsgIm;
import org.apache.ibatis.annotations.Param;

public interface GroupMsgImMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_group_msg
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_group_msg
     *
     * @mbg.generated
     */
    int insert(GroupMsgIm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_group_msg
     *
     * @mbg.generated
     */
    int insertSelective(GroupMsgIm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_group_msg
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    GroupMsgIm selectByPrimaryKeySelective(@Param("id") Long id, @Param("selective") GroupMsgIm.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_group_msg
     *
     * @mbg.generated
     */
    GroupMsgIm selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_group_msg
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GroupMsgIm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_group_msg
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(GroupMsgIm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_group_msg
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GroupMsgIm record);
}