package com.netty4.server.mapper;

import com.netty4.server.entity.groupPrivateMsgImr;
import org.apache.ibatis.annotations.Param;

public interface groupPrivateMsgImrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imr_group_private_msg
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imr_group_private_msg
     *
     * @mbg.generated
     */
    int insert(groupPrivateMsgImr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imr_group_private_msg
     *
     * @mbg.generated
     */
    int insertSelective(groupPrivateMsgImr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imr_group_private_msg
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    groupPrivateMsgImr selectByPrimaryKeySelective(@Param("id") Long id, @Param("selective") groupPrivateMsgImr.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imr_group_private_msg
     *
     * @mbg.generated
     */
    groupPrivateMsgImr selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imr_group_private_msg
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(groupPrivateMsgImr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imr_group_private_msg
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(groupPrivateMsgImr record);
}