package com.netty4.server.mapper;

import com.netty4.server.entity.GroupUserImr;
import org.apache.ibatis.annotations.Param;

public interface GroupUserImrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imr_group_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imr_group_user
     *
     * @mbg.generated
     */
    int insert(GroupUserImr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imr_group_user
     *
     * @mbg.generated
     */
    int insertSelective(GroupUserImr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imr_group_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    GroupUserImr selectByPrimaryKeySelective(@Param("id") Long id, @Param("selective") GroupUserImr.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imr_group_user
     *
     * @mbg.generated
     */
    GroupUserImr selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imr_group_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GroupUserImr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imr_group_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GroupUserImr record);
}