package com.netty4.server.mapper;

import com.netty4.server.entity.GroupMsgGroupImr;
import org.apache.ibatis.annotations.Param;

public interface GroupMsgGroupImrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imr_group_msg_group
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imr_group_msg_group
     *
     * @mbg.generated
     */
    int insert(GroupMsgGroupImr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imr_group_msg_group
     *
     * @mbg.generated
     */
    int insertSelective(GroupMsgGroupImr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imr_group_msg_group
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    GroupMsgGroupImr selectByPrimaryKeySelective(@Param("id") Long id, @Param("selective") GroupMsgGroupImr.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imr_group_msg_group
     *
     * @mbg.generated
     */
    GroupMsgGroupImr selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imr_group_msg_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GroupMsgGroupImr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imr_group_msg_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GroupMsgGroupImr record);
}