package com.netty4.server.mapper;

import com.netty4.server.entity.MessageTypeIm;
import org.apache.ibatis.annotations.Param;

public interface MessageTypeImMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_message_type
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_message_type
     *
     * @mbg.generated
     */
    int insert(MessageTypeIm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_message_type
     *
     * @mbg.generated
     */
    int insertSelective(MessageTypeIm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_message_type
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MessageTypeIm selectByPrimaryKeySelective(@Param("id") Long id, @Param("selective") MessageTypeIm.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_message_type
     *
     * @mbg.generated
     */
    MessageTypeIm selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_message_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MessageTypeIm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_message_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MessageTypeIm record);
}