package com.netty4.server.mapper;

import com.netty4.server.entity.MessageIm;
import org.apache.ibatis.annotations.Param;

public interface MessageImMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_message
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_message
     *
     * @mbg.generated
     */
    int insert(MessageIm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_message
     *
     * @mbg.generated
     */
    int insertSelective(MessageIm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_message
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MessageIm selectByPrimaryKeySelective(@Param("id") Long id, @Param("selective") MessageIm.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_message
     *
     * @mbg.generated
     */
    MessageIm selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_message
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MessageIm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_message
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(MessageIm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_message
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MessageIm record);
}