package com.netty4.server.mapper;

import com.netty4.server.entity.Nation;
import org.apache.ibatis.annotations.Param;

public interface NationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_nation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_nation
     *
     * @mbg.generated
     */
    int insert(Nation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_nation
     *
     * @mbg.generated
     */
    int insertSelective(Nation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_nation
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Nation selectByPrimaryKeySelective(@Param("id") Long id, @Param("selective") Nation.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_nation
     *
     * @mbg.generated
     */
    Nation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_nation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Nation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_nation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Nation record);
}