package com.netty4.server.mapper;

import com.netty4.server.entity.Province;
import org.apache.ibatis.annotations.Param;

public interface ProvinceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_province
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_province
     *
     * @mbg.generated
     */
    int insert(Province record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_province
     *
     * @mbg.generated
     */
    int insertSelective(Province record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_province
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Province selectByPrimaryKeySelective(@Param("id") Long id, @Param("selective") Province.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_province
     *
     * @mbg.generated
     */
    Province selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_province
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Province record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_province
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Province record);
}