package com.netty4.server.mapper;

import com.netty4.server.entity.UserGroupIm;
import org.apache.ibatis.annotations.Param;

public interface UserGroupImMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_user_group
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_user_group
     *
     * @mbg.generated
     */
    int insert(UserGroupIm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_user_group
     *
     * @mbg.generated
     */
    int insertSelective(UserGroupIm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_user_group
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    UserGroupIm selectByPrimaryKeySelective(@Param("id") Long id, @Param("selective") UserGroupIm.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_user_group
     *
     * @mbg.generated
     */
    UserGroupIm selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_user_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserGroupIm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_user_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserGroupIm record);
}