package com.netty4.server.entity;

public class FriendShipPolicyIm {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_friend_ship_policy.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_friend_ship_policy.friend_ship_policy
     *
     * @mbg.generated
     */
    private String friendShipPolicy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_friend_ship_policy.id
     *
     * @return the value of im_friend_ship_policy.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_friend_ship_policy.id
     *
     * @param id the value for im_friend_ship_policy.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_friend_ship_policy.friend_ship_policy
     *
     * @return the value of im_friend_ship_policy.friend_ship_policy
     *
     * @mbg.generated
     */
    public String getFriendShipPolicy() {
        return friendShipPolicy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_friend_ship_policy.friend_ship_policy
     *
     * @param friendShipPolicy the value for im_friend_ship_policy.friend_ship_policy
     *
     * @mbg.generated
     */
    public void setFriendShipPolicy(String friendShipPolicy) {
        this.friendShipPolicy = friendShipPolicy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_friend_ship_policy
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", friendShipPolicy=").append(friendShipPolicy);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_friend_ship_policy
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        FriendShipPolicyIm other = (FriendShipPolicyIm) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getFriendShipPolicy() == null ? other.getFriendShipPolicy() == null : this.getFriendShipPolicy().equals(other.getFriendShipPolicy()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_friend_ship_policy
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getFriendShipPolicy() == null) ? 0 : getFriendShipPolicy().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table im_friend_ship_policy
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id", "id", "BIGINT"),
        friendShipPolicy("friend_ship_policy", "friendShipPolicy", "VARCHAR");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table im_friend_ship_policy
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table im_friend_ship_policy
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table im_friend_ship_policy
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table im_friend_ship_policy
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table im_friend_ship_policy
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table im_friend_ship_policy
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table im_friend_ship_policy
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table im_friend_ship_policy
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table im_friend_ship_policy
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.column + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table im_friend_ship_policy
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.column + " ASC";
        }
    }
}