package com.netty4.server.entity;

public class FriendIm {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_friend.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_friend.fk_firend_id
     *
     * @mbg.generated
     */
    private Long fkFirendId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_friend.fk_user_id
     *
     * @mbg.generated
     */
    private Long fkUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_friend.friend_nick
     *
     * @mbg.generated
     */
    private String friendNick;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_friend.fk_friend_type_id
     *
     * @mbg.generated
     */
    private Long fkFriendTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_friend.fk_friend_group_id
     *
     * @mbg.generated
     */
    private Long fkFriendGroupId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_friend.id
     *
     * @return the value of im_friend.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_friend.id
     *
     * @param id the value for im_friend.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_friend.fk_firend_id
     *
     * @return the value of im_friend.fk_firend_id
     *
     * @mbg.generated
     */
    public Long getFkFirendId() {
        return fkFirendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_friend.fk_firend_id
     *
     * @param fkFirendId the value for im_friend.fk_firend_id
     *
     * @mbg.generated
     */
    public void setFkFirendId(Long fkFirendId) {
        this.fkFirendId = fkFirendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_friend.fk_user_id
     *
     * @return the value of im_friend.fk_user_id
     *
     * @mbg.generated
     */
    public Long getFkUserId() {
        return fkUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_friend.fk_user_id
     *
     * @param fkUserId the value for im_friend.fk_user_id
     *
     * @mbg.generated
     */
    public void setFkUserId(Long fkUserId) {
        this.fkUserId = fkUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_friend.friend_nick
     *
     * @return the value of im_friend.friend_nick
     *
     * @mbg.generated
     */
    public String getFriendNick() {
        return friendNick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_friend.friend_nick
     *
     * @param friendNick the value for im_friend.friend_nick
     *
     * @mbg.generated
     */
    public void setFriendNick(String friendNick) {
        this.friendNick = friendNick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_friend.fk_friend_type_id
     *
     * @return the value of im_friend.fk_friend_type_id
     *
     * @mbg.generated
     */
    public Long getFkFriendTypeId() {
        return fkFriendTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_friend.fk_friend_type_id
     *
     * @param fkFriendTypeId the value for im_friend.fk_friend_type_id
     *
     * @mbg.generated
     */
    public void setFkFriendTypeId(Long fkFriendTypeId) {
        this.fkFriendTypeId = fkFriendTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_friend.fk_friend_group_id
     *
     * @return the value of im_friend.fk_friend_group_id
     *
     * @mbg.generated
     */
    public Long getFkFriendGroupId() {
        return fkFriendGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_friend.fk_friend_group_id
     *
     * @param fkFriendGroupId the value for im_friend.fk_friend_group_id
     *
     * @mbg.generated
     */
    public void setFkFriendGroupId(Long fkFriendGroupId) {
        this.fkFriendGroupId = fkFriendGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_friend
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", fkFirendId=").append(fkFirendId);
        sb.append(", fkUserId=").append(fkUserId);
        sb.append(", friendNick=").append(friendNick);
        sb.append(", fkFriendTypeId=").append(fkFriendTypeId);
        sb.append(", fkFriendGroupId=").append(fkFriendGroupId);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_friend
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        FriendIm other = (FriendIm) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getFkFirendId() == null ? other.getFkFirendId() == null : this.getFkFirendId().equals(other.getFkFirendId()))
            && (this.getFkUserId() == null ? other.getFkUserId() == null : this.getFkUserId().equals(other.getFkUserId()))
            && (this.getFriendNick() == null ? other.getFriendNick() == null : this.getFriendNick().equals(other.getFriendNick()))
            && (this.getFkFriendTypeId() == null ? other.getFkFriendTypeId() == null : this.getFkFriendTypeId().equals(other.getFkFriendTypeId()))
            && (this.getFkFriendGroupId() == null ? other.getFkFriendGroupId() == null : this.getFkFriendGroupId().equals(other.getFkFriendGroupId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_friend
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getFkFirendId() == null) ? 0 : getFkFirendId().hashCode());
        result = prime * result + ((getFkUserId() == null) ? 0 : getFkUserId().hashCode());
        result = prime * result + ((getFriendNick() == null) ? 0 : getFriendNick().hashCode());
        result = prime * result + ((getFkFriendTypeId() == null) ? 0 : getFkFriendTypeId().hashCode());
        result = prime * result + ((getFkFriendGroupId() == null) ? 0 : getFkFriendGroupId().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table im_friend
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id", "id", "BIGINT"),
        fkFirendId("fk_firend_id", "fkFirendId", "BIGINT"),
        fkUserId("fk_user_id", "fkUserId", "BIGINT"),
        friendNick("friend_nick", "friendNick", "VARCHAR"),
        fkFriendTypeId("fk_friend_type_id", "fkFriendTypeId", "BIGINT"),
        fkFriendGroupId("fk_friend_group_id", "fkFriendGroupId", "BIGINT");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table im_friend
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table im_friend
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table im_friend
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table im_friend
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table im_friend
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table im_friend
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table im_friend
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table im_friend
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table im_friend
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.column + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table im_friend
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.column + " ASC";
        }
    }
}