package com.netty4.server.entity;

import java.util.Date;

public class GroupUserImr {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imr_group_user.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imr_group_user.fk_user_id
     *
     * @mbg.generated
     */
    private Long fkUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imr_group_user.fk_group_id
     *
     * @mbg.generated
     */
    private Long fkGroupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imr_group_user.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imr_group_user.group_nick
     *
     * @mbg.generated
     */
    private String groupNick;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imr_group_user.id
     *
     * @return the value of imr_group_user.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imr_group_user.id
     *
     * @param id the value for imr_group_user.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imr_group_user.fk_user_id
     *
     * @return the value of imr_group_user.fk_user_id
     *
     * @mbg.generated
     */
    public Long getFkUserId() {
        return fkUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imr_group_user.fk_user_id
     *
     * @param fkUserId the value for imr_group_user.fk_user_id
     *
     * @mbg.generated
     */
    public void setFkUserId(Long fkUserId) {
        this.fkUserId = fkUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imr_group_user.fk_group_id
     *
     * @return the value of imr_group_user.fk_group_id
     *
     * @mbg.generated
     */
    public Long getFkGroupId() {
        return fkGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imr_group_user.fk_group_id
     *
     * @param fkGroupId the value for imr_group_user.fk_group_id
     *
     * @mbg.generated
     */
    public void setFkGroupId(Long fkGroupId) {
        this.fkGroupId = fkGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imr_group_user.create_time
     *
     * @return the value of imr_group_user.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imr_group_user.create_time
     *
     * @param createTime the value for imr_group_user.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imr_group_user.group_nick
     *
     * @return the value of imr_group_user.group_nick
     *
     * @mbg.generated
     */
    public String getGroupNick() {
        return groupNick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imr_group_user.group_nick
     *
     * @param groupNick the value for imr_group_user.group_nick
     *
     * @mbg.generated
     */
    public void setGroupNick(String groupNick) {
        this.groupNick = groupNick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imr_group_user
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", fkUserId=").append(fkUserId);
        sb.append(", fkGroupId=").append(fkGroupId);
        sb.append(", createTime=").append(createTime);
        sb.append(", groupNick=").append(groupNick);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imr_group_user
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        GroupUserImr other = (GroupUserImr) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getFkUserId() == null ? other.getFkUserId() == null : this.getFkUserId().equals(other.getFkUserId()))
            && (this.getFkGroupId() == null ? other.getFkGroupId() == null : this.getFkGroupId().equals(other.getFkGroupId()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getGroupNick() == null ? other.getGroupNick() == null : this.getGroupNick().equals(other.getGroupNick()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imr_group_user
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getFkUserId() == null) ? 0 : getFkUserId().hashCode());
        result = prime * result + ((getFkGroupId() == null) ? 0 : getFkGroupId().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getGroupNick() == null) ? 0 : getGroupNick().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table imr_group_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id", "id", "BIGINT"),
        fkUserId("fk_user_id", "fkUserId", "BIGINT"),
        fkGroupId("fk_group_id", "fkGroupId", "BIGINT"),
        createTime("create_time", "createTime", "java.time.LocalDateTime"),
        groupNick("group_nick", "groupNick", "VARCHAR");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table imr_group_user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table imr_group_user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table imr_group_user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table imr_group_user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table imr_group_user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table imr_group_user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table imr_group_user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table imr_group_user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table imr_group_user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.column + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table imr_group_user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.column + " ASC";
        }
    }
}