package com.netty4.server.entity;

import java.util.Date;

public class groupPrivateMsgImr {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imr_group_private_msg.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imr_group_private_msg.fk_from_id
     *
     * @mbg.generated
     */
    private Long fkFromId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imr_group_private_msg.from_nick
     *
     * @mbg.generated
     */
    private String fromNick;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imr_group_private_msg.fk_to_id
     *
     * @mbg.generated
     */
    private Long fkToId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imr_group_private_msg.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imr_group_private_msg.state
     *
     * @mbg.generated
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imr_group_private_msg.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imr_group_private_msg.kf_group_id
     *
     * @mbg.generated
     */
    private Long kfGroupId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imr_group_private_msg.id
     *
     * @return the value of imr_group_private_msg.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imr_group_private_msg.id
     *
     * @param id the value for imr_group_private_msg.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imr_group_private_msg.fk_from_id
     *
     * @return the value of imr_group_private_msg.fk_from_id
     *
     * @mbg.generated
     */
    public Long getFkFromId() {
        return fkFromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imr_group_private_msg.fk_from_id
     *
     * @param fkFromId the value for imr_group_private_msg.fk_from_id
     *
     * @mbg.generated
     */
    public void setFkFromId(Long fkFromId) {
        this.fkFromId = fkFromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imr_group_private_msg.from_nick
     *
     * @return the value of imr_group_private_msg.from_nick
     *
     * @mbg.generated
     */
    public String getFromNick() {
        return fromNick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imr_group_private_msg.from_nick
     *
     * @param fromNick the value for imr_group_private_msg.from_nick
     *
     * @mbg.generated
     */
    public void setFromNick(String fromNick) {
        this.fromNick = fromNick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imr_group_private_msg.fk_to_id
     *
     * @return the value of imr_group_private_msg.fk_to_id
     *
     * @mbg.generated
     */
    public Long getFkToId() {
        return fkToId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imr_group_private_msg.fk_to_id
     *
     * @param fkToId the value for imr_group_private_msg.fk_to_id
     *
     * @mbg.generated
     */
    public void setFkToId(Long fkToId) {
        this.fkToId = fkToId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imr_group_private_msg.content
     *
     * @return the value of imr_group_private_msg.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imr_group_private_msg.content
     *
     * @param content the value for imr_group_private_msg.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imr_group_private_msg.state
     *
     * @return the value of imr_group_private_msg.state
     *
     * @mbg.generated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imr_group_private_msg.state
     *
     * @param state the value for imr_group_private_msg.state
     *
     * @mbg.generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imr_group_private_msg.create_time
     *
     * @return the value of imr_group_private_msg.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imr_group_private_msg.create_time
     *
     * @param createTime the value for imr_group_private_msg.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imr_group_private_msg.kf_group_id
     *
     * @return the value of imr_group_private_msg.kf_group_id
     *
     * @mbg.generated
     */
    public Long getKfGroupId() {
        return kfGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imr_group_private_msg.kf_group_id
     *
     * @param kfGroupId the value for imr_group_private_msg.kf_group_id
     *
     * @mbg.generated
     */
    public void setKfGroupId(Long kfGroupId) {
        this.kfGroupId = kfGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imr_group_private_msg
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", fkFromId=").append(fkFromId);
        sb.append(", fromNick=").append(fromNick);
        sb.append(", fkToId=").append(fkToId);
        sb.append(", content=").append(content);
        sb.append(", state=").append(state);
        sb.append(", createTime=").append(createTime);
        sb.append(", kfGroupId=").append(kfGroupId);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imr_group_private_msg
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        groupPrivateMsgImr other = (groupPrivateMsgImr) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getFkFromId() == null ? other.getFkFromId() == null : this.getFkFromId().equals(other.getFkFromId()))
            && (this.getFromNick() == null ? other.getFromNick() == null : this.getFromNick().equals(other.getFromNick()))
            && (this.getFkToId() == null ? other.getFkToId() == null : this.getFkToId().equals(other.getFkToId()))
            && (this.getContent() == null ? other.getContent() == null : this.getContent().equals(other.getContent()))
            && (this.getState() == null ? other.getState() == null : this.getState().equals(other.getState()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getKfGroupId() == null ? other.getKfGroupId() == null : this.getKfGroupId().equals(other.getKfGroupId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imr_group_private_msg
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getFkFromId() == null) ? 0 : getFkFromId().hashCode());
        result = prime * result + ((getFromNick() == null) ? 0 : getFromNick().hashCode());
        result = prime * result + ((getFkToId() == null) ? 0 : getFkToId().hashCode());
        result = prime * result + ((getContent() == null) ? 0 : getContent().hashCode());
        result = prime * result + ((getState() == null) ? 0 : getState().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getKfGroupId() == null) ? 0 : getKfGroupId().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table imr_group_private_msg
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id", "id", "BIGINT"),
        fkFromId("fk_from_id", "fkFromId", "BIGINT"),
        fromNick("from_nick", "fromNick", "VARCHAR"),
        fkToId("fk_to_id", "fkToId", "BIGINT"),
        content("content", "content", "VARCHAR"),
        state("state", "state", "INTEGER"),
        createTime("create_time", "createTime", "java.time.LocalDateTime"),
        kfGroupId("kf_group_id", "kfGroupId", "BIGINT");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table imr_group_private_msg
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table imr_group_private_msg
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table imr_group_private_msg
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table imr_group_private_msg
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table imr_group_private_msg
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table imr_group_private_msg
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table imr_group_private_msg
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table imr_group_private_msg
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table imr_group_private_msg
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.column + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table imr_group_private_msg
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.column + " ASC";
        }
    }
}