package com.netty4.server.entity;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.login_name
     *
     * @mbg.generated
     */
    private String loginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.nickname
     *
     * @mbg.generated
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.signa_ture
     *
     * @mbg.generated
     */
    private String signaTure;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.sex
     *
     * @mbg.generated
     */
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.birthday
     *
     * @mbg.generated
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.realname
     *
     * @mbg.generated
     */
    private String realname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.intro
     *
     * @mbg.generated
     */
    private String intro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.head_portrait
     *
     * @mbg.generated
     */
    private String headPortrait;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.age
     *
     * @mbg.generated
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.constellation
     *
     * @mbg.generated
     */
    private String constellation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.blood_type
     *
     * @mbg.generated
     */
    private String bloodType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.fk_nation_id
     *
     * @mbg.generated
     */
    private Long fkNationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.fk_province_id
     *
     * @mbg.generated
     */
    private Long fkProvinceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.fk_city_id
     *
     * @mbg.generated
     */
    private Long fkCityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.fk_frd_policy_id
     *
     * @mbg.generated
     */
    private Long fkFrdPolicyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.fk_user_state_id
     *
     * @mbg.generated
     */
    private Long fkUserStateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.delete
     *
     * @mbg.generated
     */
    private Boolean delete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.id
     *
     * @return the value of s_user.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.id
     *
     * @param id the value for s_user.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.login_name
     *
     * @return the value of s_user.login_name
     *
     * @mbg.generated
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.login_name
     *
     * @param loginName the value for s_user.login_name
     *
     * @mbg.generated
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.nickname
     *
     * @return the value of s_user.nickname
     *
     * @mbg.generated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.nickname
     *
     * @param nickname the value for s_user.nickname
     *
     * @mbg.generated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.password
     *
     * @return the value of s_user.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.password
     *
     * @param password the value for s_user.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.signa_ture
     *
     * @return the value of s_user.signa_ture
     *
     * @mbg.generated
     */
    public String getSignaTure() {
        return signaTure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.signa_ture
     *
     * @param signaTure the value for s_user.signa_ture
     *
     * @mbg.generated
     */
    public void setSignaTure(String signaTure) {
        this.signaTure = signaTure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.sex
     *
     * @return the value of s_user.sex
     *
     * @mbg.generated
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.sex
     *
     * @param sex the value for s_user.sex
     *
     * @mbg.generated
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.birthday
     *
     * @return the value of s_user.birthday
     *
     * @mbg.generated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.birthday
     *
     * @param birthday the value for s_user.birthday
     *
     * @mbg.generated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.realname
     *
     * @return the value of s_user.realname
     *
     * @mbg.generated
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.realname
     *
     * @param realname the value for s_user.realname
     *
     * @mbg.generated
     */
    public void setRealname(String realname) {
        this.realname = realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.email
     *
     * @return the value of s_user.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.email
     *
     * @param email the value for s_user.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.intro
     *
     * @return the value of s_user.intro
     *
     * @mbg.generated
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.intro
     *
     * @param intro the value for s_user.intro
     *
     * @mbg.generated
     */
    public void setIntro(String intro) {
        this.intro = intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.head_portrait
     *
     * @return the value of s_user.head_portrait
     *
     * @mbg.generated
     */
    public String getHeadPortrait() {
        return headPortrait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.head_portrait
     *
     * @param headPortrait the value for s_user.head_portrait
     *
     * @mbg.generated
     */
    public void setHeadPortrait(String headPortrait) {
        this.headPortrait = headPortrait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.age
     *
     * @return the value of s_user.age
     *
     * @mbg.generated
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.age
     *
     * @param age the value for s_user.age
     *
     * @mbg.generated
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.constellation
     *
     * @return the value of s_user.constellation
     *
     * @mbg.generated
     */
    public String getConstellation() {
        return constellation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.constellation
     *
     * @param constellation the value for s_user.constellation
     *
     * @mbg.generated
     */
    public void setConstellation(String constellation) {
        this.constellation = constellation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.blood_type
     *
     * @return the value of s_user.blood_type
     *
     * @mbg.generated
     */
    public String getBloodType() {
        return bloodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.blood_type
     *
     * @param bloodType the value for s_user.blood_type
     *
     * @mbg.generated
     */
    public void setBloodType(String bloodType) {
        this.bloodType = bloodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.fk_nation_id
     *
     * @return the value of s_user.fk_nation_id
     *
     * @mbg.generated
     */
    public Long getFkNationId() {
        return fkNationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.fk_nation_id
     *
     * @param fkNationId the value for s_user.fk_nation_id
     *
     * @mbg.generated
     */
    public void setFkNationId(Long fkNationId) {
        this.fkNationId = fkNationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.fk_province_id
     *
     * @return the value of s_user.fk_province_id
     *
     * @mbg.generated
     */
    public Long getFkProvinceId() {
        return fkProvinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.fk_province_id
     *
     * @param fkProvinceId the value for s_user.fk_province_id
     *
     * @mbg.generated
     */
    public void setFkProvinceId(Long fkProvinceId) {
        this.fkProvinceId = fkProvinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.fk_city_id
     *
     * @return the value of s_user.fk_city_id
     *
     * @mbg.generated
     */
    public Long getFkCityId() {
        return fkCityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.fk_city_id
     *
     * @param fkCityId the value for s_user.fk_city_id
     *
     * @mbg.generated
     */
    public void setFkCityId(Long fkCityId) {
        this.fkCityId = fkCityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.fk_frd_policy_id
     *
     * @return the value of s_user.fk_frd_policy_id
     *
     * @mbg.generated
     */
    public Long getFkFrdPolicyId() {
        return fkFrdPolicyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.fk_frd_policy_id
     *
     * @param fkFrdPolicyId the value for s_user.fk_frd_policy_id
     *
     * @mbg.generated
     */
    public void setFkFrdPolicyId(Long fkFrdPolicyId) {
        this.fkFrdPolicyId = fkFrdPolicyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.fk_user_state_id
     *
     * @return the value of s_user.fk_user_state_id
     *
     * @mbg.generated
     */
    public Long getFkUserStateId() {
        return fkUserStateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.fk_user_state_id
     *
     * @param fkUserStateId the value for s_user.fk_user_state_id
     *
     * @mbg.generated
     */
    public void setFkUserStateId(Long fkUserStateId) {
        this.fkUserStateId = fkUserStateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.delete
     *
     * @return the value of s_user.delete
     *
     * @mbg.generated
     */
    public Boolean getDelete() {
        return delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.delete
     *
     * @param delete the value for s_user.delete
     *
     * @mbg.generated
     */
    public void setDelete(Boolean delete) {
        this.delete = delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", loginName=").append(loginName);
        sb.append(", nickname=").append(nickname);
        sb.append(", password=").append(password);
        sb.append(", signaTure=").append(signaTure);
        sb.append(", sex=").append(sex);
        sb.append(", birthday=").append(birthday);
        sb.append(", realname=").append(realname);
        sb.append(", email=").append(email);
        sb.append(", intro=").append(intro);
        sb.append(", headPortrait=").append(headPortrait);
        sb.append(", age=").append(age);
        sb.append(", constellation=").append(constellation);
        sb.append(", bloodType=").append(bloodType);
        sb.append(", fkNationId=").append(fkNationId);
        sb.append(", fkProvinceId=").append(fkProvinceId);
        sb.append(", fkCityId=").append(fkCityId);
        sb.append(", fkFrdPolicyId=").append(fkFrdPolicyId);
        sb.append(", fkUserStateId=").append(fkUserStateId);
        sb.append(", delete=").append(delete);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        User other = (User) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getLoginName() == null ? other.getLoginName() == null : this.getLoginName().equals(other.getLoginName()))
            && (this.getNickname() == null ? other.getNickname() == null : this.getNickname().equals(other.getNickname()))
            && (this.getPassword() == null ? other.getPassword() == null : this.getPassword().equals(other.getPassword()))
            && (this.getSignaTure() == null ? other.getSignaTure() == null : this.getSignaTure().equals(other.getSignaTure()))
            && (this.getSex() == null ? other.getSex() == null : this.getSex().equals(other.getSex()))
            && (this.getBirthday() == null ? other.getBirthday() == null : this.getBirthday().equals(other.getBirthday()))
            && (this.getRealname() == null ? other.getRealname() == null : this.getRealname().equals(other.getRealname()))
            && (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
            && (this.getIntro() == null ? other.getIntro() == null : this.getIntro().equals(other.getIntro()))
            && (this.getHeadPortrait() == null ? other.getHeadPortrait() == null : this.getHeadPortrait().equals(other.getHeadPortrait()))
            && (this.getAge() == null ? other.getAge() == null : this.getAge().equals(other.getAge()))
            && (this.getConstellation() == null ? other.getConstellation() == null : this.getConstellation().equals(other.getConstellation()))
            && (this.getBloodType() == null ? other.getBloodType() == null : this.getBloodType().equals(other.getBloodType()))
            && (this.getFkNationId() == null ? other.getFkNationId() == null : this.getFkNationId().equals(other.getFkNationId()))
            && (this.getFkProvinceId() == null ? other.getFkProvinceId() == null : this.getFkProvinceId().equals(other.getFkProvinceId()))
            && (this.getFkCityId() == null ? other.getFkCityId() == null : this.getFkCityId().equals(other.getFkCityId()))
            && (this.getFkFrdPolicyId() == null ? other.getFkFrdPolicyId() == null : this.getFkFrdPolicyId().equals(other.getFkFrdPolicyId()))
            && (this.getFkUserStateId() == null ? other.getFkUserStateId() == null : this.getFkUserStateId().equals(other.getFkUserStateId()))
            && (this.getDelete() == null ? other.getDelete() == null : this.getDelete().equals(other.getDelete()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getLoginName() == null) ? 0 : getLoginName().hashCode());
        result = prime * result + ((getNickname() == null) ? 0 : getNickname().hashCode());
        result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
        result = prime * result + ((getSignaTure() == null) ? 0 : getSignaTure().hashCode());
        result = prime * result + ((getSex() == null) ? 0 : getSex().hashCode());
        result = prime * result + ((getBirthday() == null) ? 0 : getBirthday().hashCode());
        result = prime * result + ((getRealname() == null) ? 0 : getRealname().hashCode());
        result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
        result = prime * result + ((getIntro() == null) ? 0 : getIntro().hashCode());
        result = prime * result + ((getHeadPortrait() == null) ? 0 : getHeadPortrait().hashCode());
        result = prime * result + ((getAge() == null) ? 0 : getAge().hashCode());
        result = prime * result + ((getConstellation() == null) ? 0 : getConstellation().hashCode());
        result = prime * result + ((getBloodType() == null) ? 0 : getBloodType().hashCode());
        result = prime * result + ((getFkNationId() == null) ? 0 : getFkNationId().hashCode());
        result = prime * result + ((getFkProvinceId() == null) ? 0 : getFkProvinceId().hashCode());
        result = prime * result + ((getFkCityId() == null) ? 0 : getFkCityId().hashCode());
        result = prime * result + ((getFkFrdPolicyId() == null) ? 0 : getFkFrdPolicyId().hashCode());
        result = prime * result + ((getFkUserStateId() == null) ? 0 : getFkUserStateId().hashCode());
        result = prime * result + ((getDelete() == null) ? 0 : getDelete().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table s_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id", "id", "BIGINT"),
        loginName("login_name", "loginName", "VARCHAR"),
        nickname("nickname", "nickname", "VARCHAR"),
        password("password", "password", "VARCHAR"),
        signaTure("signa_ture", "signaTure", "VARCHAR"),
        sex("sex", "sex", "INTEGER"),
        birthday("birthday", "birthday", "java.time.LocalDateTime"),
        realname("realname", "realname", "VARCHAR"),
        email("email", "email", "VARCHAR"),
        intro("intro", "intro", "VARCHAR"),
        headPortrait("head_portrait", "headPortrait", "VARCHAR"),
        age("age", "age", "INTEGER"),
        constellation("constellation", "constellation", "CHAR"),
        bloodType("blood_type", "bloodType", "VARCHAR"),
        fkNationId("fk_nation_id", "fkNationId", "BIGINT"),
        fkProvinceId("fk_province_id", "fkProvinceId", "BIGINT"),
        fkCityId("fk_city_id", "fkCityId", "BIGINT"),
        fkFrdPolicyId("fk_frd_policy_id", "fkFrdPolicyId", "BIGINT"),
        fkUserStateId("fk_user_state_id", "fkUserStateId", "BIGINT"),
        delete("delete", "delete", "BIT");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table s_user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table s_user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table s_user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table s_user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table s_user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table s_user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table s_user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table s_user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table s_user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.column + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table s_user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.column + " ASC";
        }
    }
}